name: "Deploy to GitHub Pages"

on:
  push:
    branches:
      - main 

permissions:
  actions: read
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Use Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: "Install dependencies"
        run: npm ci

      - name: "Build"
        run: npm run build

      - name: "Debug - show repo root (quick)"
        run: |
          echo "=== repo root files ==="
          ls -la

      - name: "Debug - show dist contents and index head"
        run: |
          echo "=== dist listing ==="
          ls -la ./dist || true
          echo "=== dist top of index.html ==="
          sed -n '1,120p' ./dist/index.html || true

      - name: "Upload Pages artifact"
        id: upload-pages-artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: "Deploy to GitHub Pages"
        uses: actions/deploy-pages@v4
